---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates (CentOS)
    tags: always
    dnf:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'  

  - name: install updates (Ubuntu)
    tags: always
    apt:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == 'Ubuntu'   

- hosts: all
  become: true
  roles:
  - role: base

- hosts: workstations
  tags: workstation
  become: true
  roles:
  - role: workstations

- hosts: web_servers
  become: true
  roles:
  - role: web_servers

- hosts: db_servers
  become: true
  roles:
  - role: db_servers